"""Pre-warmed plans for known questions, so they need no LLM call (Phase 10b).

    python -m app.plan_seed export   # developer: disk plan cache -> backend/plan_seed.json
    python -m app.plan_seed load     # image build (via prepare_sample): seed -> sample cache

export copies, for each known question (the example chips, the eval questions and the golden
anchors), the plan already in the disk plan cache under today's key. Only plans the latest
full eval scored correct are exported, so a misread is never frozen in. The file is generated:
never edit it by hand.

load writes each entry into <sample cache>/plan_seed/ with the same file name as the disk
cache uses for that key. The planner reads it after its own caches. An entry made for another
prompt version or another file never matches a key, so it can only go stale, never wrong.
Retention never touches the sample cache, so the seed is never deleted.
"""

import json
import sys
from pathlib import Path
from typing import Any

from app.api.sample import get_sample_cache_dir, read_cached_sample
from app.core import planner, storage

BACKEND = Path(__file__).resolve().parents[1]
SEED_FILE = BACKEND / "plan_seed.json"
EVAL_DIR = BACKEND.parent / "eval"
RESULTS_FILE = EVAL_DIR / "results" / "latest.json"
HEADER = "Generated by python -m app.plan_seed export from the disk plan cache. Do not edit."
# The example chips' wording, as in frontend/src/lib/plan.ts (EXAMPLES).
CHIP_QUESTIONS = ["Top 5 states by revenue", "Monthly revenue trend",
                  "Cancellation rate by fulfilment", "Top categories by revenue"]


def known_questions() -> list[str]:
    """Chip questions, then the eval questions, then the golden anchors' questions."""
    import yaml  # export is a developer step; the runtime image only loads the seed

    questions = yaml.safe_load((EVAL_DIR / "questions.yaml").read_text(encoding="utf-8"))
    golden = yaml.safe_load((EVAL_DIR / "golden.yaml").read_text(encoding="utf-8"))
    out = CHIP_QUESTIONS + [q["question"] for q in questions["questions"]]
    out += [a["question"] for a in golden["anchors"]]
    return list(dict.fromkeys(out))


def scored(results_file: Path) -> dict[str, bool]:
    """question -> correct, from a full eval run (partial runs are refused)."""
    results = json.loads(results_file.read_text(encoding="utf-8"))
    if results["meta"].get("stopped") or results["meta"].get("needs_fresh_run"):
        raise SystemExit(f"{results_file.name} is not a complete eval run; run eval.py first.")
    return {row["question"]: bool(row["correct"]) for row in results["rows"]}


def export(cache: Path, results_file: Path = RESULTS_FILE, out: Path = SEED_FILE) -> dict:
    """Write the seed from the disk plan cache; returns counts for the report."""
    sample = read_cached_sample(cache)
    if sample is None:
        raise SystemExit("No prepared sample. Run python -m app.prepare_sample first.")
    context = planner.build_context(sample.dataset_id, storage.storage_root(), cache)
    correct = scored(results_file)
    entries: list[dict[str, Any]] = []
    skipped = {"not cached": 0, "scored wrong": 0}
    for question in known_questions():
        if question in correct and not correct[question]:
            skipped["scored wrong"] += 1
            continue
        key = planner.cache_key(context.prompt, question)
        if any(e["normalised"] == key[2] for e in entries):
            continue  # same question after normalising (e.g. a chip that is also an eval question)
        saved = planner.read_disk(key)
        if saved is None:
            skipped["not cached"] += 1
            continue
        entries.append({"question": question, "prompt_version": key[0], "schema_hash": key[1],
                        "normalised": key[2], "plan": saved.plan.model_dump(mode="json"),
                        "caveats": saved.caveats})
    entries.sort(key=lambda e: e["normalised"])
    out.write_text(json.dumps({"_comment": HEADER, "entries": entries}, indent=1,
                              ensure_ascii=False) + "\n", encoding="utf-8")
    return {"exported": len(entries), **skipped}


def load(cache: Path, seed_file: Path = SEED_FILE) -> tuple[int, int]:
    """Write the seed into the sample cache; returns (entries matching today's keys, total)."""
    if not seed_file.is_file():
        return 0, 0
    entries = json.loads(seed_file.read_text(encoding="utf-8"))["entries"]
    folder = cache / planner.SEED_DIR
    folder.mkdir(parents=True, exist_ok=True)
    for entry in entries:
        key = (entry["prompt_version"], entry["schema_hash"], entry["normalised"])
        payload = {"plan": entry["plan"], "caveats": entry["caveats"],
                   "prompt_version": key[0], "schema_hash": key[1]}
        (folder / f"{planner.key_digest(key)}.json").write_text(
            json.dumps(payload, ensure_ascii=False), encoding="utf-8")
    sample = read_cached_sample(cache)
    if sample is None:
        return 0, len(entries)
    context = planner.build_context(sample.dataset_id, storage.storage_root(), cache)
    today = planner.cache_key(context.prompt, "")[:2]
    current = sum((e["prompt_version"], e["schema_hash"]) == today for e in entries)
    return current, len(entries)


def main(argv: list[str]) -> int:
    command = argv[0] if argv else ""
    cache = get_sample_cache_dir()
    if command == "export":
        counts = export(cache)
        print(f"plan seed: exported {counts['exported']} plans to {SEED_FILE.name} "
              f"({counts['not cached']} not cached, {counts['scored wrong']} scored wrong)")
        return 0
    if command == "load":
        current, total = load(cache)
        print(f"plan seed: {current} of {total} entries match the current prompt and sample")
        return 0
    print("usage: python -m app.plan_seed export|load")
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
